#!/bin/bash
#
# THIS SCRIPT RUNS AS ROOT
#
# %glacier ALL=(ALL) NOPASSWD: /usr/local/bin/glacier
########################################################################

# User configurable values

# Path to root password file
ROOTPASS_PATH="/home/mal/pkgs/glacier/rootpass"

# Files we allow to be edited with this script
VALID_TARGETS=("/etc/hosts" "$ROOTPASS_PATH")

# Delay in seconds
delay=5

########################################################################
# Here we go

# Function to check if a variable is contained in an array
contains() {
        typeset _x;
        typeset -n _A="$1"
        for _x in "${_A[@]}" ; do
                [ "$_x" = "$2" ] && return 0
        done
        return 1
}

# This variable expansion gets the basename of the path to this file
progName="${0##*/}"

# Reset PATH to known quantity
export PATH=/usr/local/bin:/bin:/usr/bin

# Force the script to run with sudo
[[ $(id -u) != 0 ]] && exec sudo "$0" "$@"

########### ALL LOGIC SHOULD BE BELOW THIS POINT ###########

# Make sure the VALID_TARGETS are files that actually exist
for valid_target in "${VALID_TARGETS[@]}"
do
    if [ ! -f $valid_target ]; then
        echo "Target not found: $valid_target"
        exit 1
    fi
done

# Flag to indicate root password query
r_flag=''

print_usage() {
  printf "Usage: glacier -r (displays rootpass) | glacier <path> (opens frozen file for editing)\n"
}

while getopts 'r' flag; do
  case "${flag}" in
    r) r_flag='true' ;;
    *) print_usage
       exit 1 ;;
  esac
done

# Handle root password query and then exit
if [[ "$r_flag" == "true" ]] ; then
    printf "ROOT PASSWORD:\n"
    cat $ROOTPASS_PATH
    exit 0
fi

# Make sure we have at least one argument
if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    print_usage
    exit 0
fi

# Get abspath of the first argument
target=`realpath $1`

# Check if the argument is a valid target
if contains VALID_TARGETS "$target" ; then
    echo "Good target: $target"
else
    echo "Bad target: $target (valid targets: ${VALID_TARGETS[@]})"
    exit 1
fi

umask 0022
tmpf=$(mktemp "/tmp/${progName}_XXXXXXXXXX")
cp -f "$target" "$tmpf"

# Revert to the original user account to edit the temporary file
chown "$SUDO_USER" "$tmpf"
sudo -u "$SUDO_USER" "${EDITOR:-vi}" "$tmpf"


#printf "############################### OLD VERS: '%s' ###############################\n\n" $target
#cat $target
#printf "\n############################### NEW VERS: '%s' ###############################\n\n" $target
#cat $tmpf
#printf "\n############################### EDITS TO: '%s' ###############################\n\n" $target
#diff --new-file $target $tmpf
#printf "\n############################### --------: '%s' ###############################\n\n" $target

# Sleep while printing time remaining
echo "Delay: $delay"
for i in $(seq 1 $delay);
do
    printf 'Waiting %d seconds...\r' $(($delay - $i))
    sleep 1
done
printf '\n'

read -t 60 -p "Are you sure you still want to edit '$target' (y/N)? " YN
[[ "${YN,,}" =~ ^(y|yes)$ ]] || exit 1

# If the copy of the file we edited ($tmpf) exists and we made nontrivial changes, apply them
if [[ -f "$tmpf" ]] && ! cmp -s "$target" "$tmpf"
then
    echo 'Applying changes'

    # Backup the target and then replace it with our edited version
    [ ! -f "$target" ] && printf "Not making backup. Target '$target' does not exist\n"
    [ -f "$target" ] && cp -pf "$target" "$target.old"
    cp -f "$tmpf" "$target"
fi

# All done
echo 'Done'
rm -f "$tmpf"
exit 0
