#!/bin/bash
#
# THIS SCRIPT RUNS AS ROOT
#
# %glacier ALL=(ALL) NOPASSWD: /usr/local/bin/myedit
########################################################################

# User configurable values

# The file to be edited
target='specialfile'
# Delay in seconds
delay=5

########################################################################
# Here we go
#
# This variable qxpansion qets the basename of the path to this file
progName="${0##*/}"

# Reset PATH to known quantity
export PATH=/usr/local/bin:/bin:/usr/bin

# Force the script to run with sudo
[[ $(id -u) != 0 ]] && exec sudo "$0" "$@"

# Sleep while printing time remaining
echo "Delay: $delay"
for i in $(seq 1 $delay);
do
    printf 'Waiting %d seconds...\r' $(($delay - $i))
    sleep 1
done
printf '\n'

read -t 60 -p "Are you sure you still want to edit $target (y/N)? " YN
[[ "${YN,,}" =~ ^(y|yes)$ ]] || exit 1

umask 0022
tmpf=$(mktemp "/tmp/${progName}_XXXXXXXXXX")
cp -f "$target" "$tmpf"

# Revert to the original user account to edit the temporary file
chown "$SUDO_USER" "$tmpf"
sudo -u "$SUDO_USER" "${EDITOR:-vi}" "$tmpf"

# If the copy of the file we edited ($tmpf) exists and we made nontrivial changes, apply them
if [[ -f "$tmpf" ]] && ! cmp -s "$target" "$tmpf"
then
    echo 'Applying changes'

    # Backup the target and then replace it with our edited version
    cp -pf "$target" "$target.old"
    cp -f "$tmpf" "$target"
fi

# All done
rm -f "$tmpf"
exit 0
